[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[terminal]

[colors.cursor]
cursor = "#f8f8f2"
text = "#282a36"

[colors.normal]
black = "#44475a"
blue = "#bd93f9"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#bbbbbb"
yellow = "#f1fa8c"

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[font]
size = 12

[font.bold]
family = "Fira Code"
style = "Bold"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"

[window]
blur = true
decorations = "full"
dynamic_padding = true
opacity = 0.75

[window.dimensions]
columns = 140
lines = 35

[keyboard]
